# Generated by Django 4.0.2 on 2022-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField()),
                ('nome_user', models.CharField(max_length=50)),
                ('motivo', models.TextField(blank=True, max_length=200)),
                ('data_inclusao', models.CharField(max_length=50)),
                ('data_pedido', models.CharField(max_length=50)),
                ('status_atual', models.CharField(max_length=50)),
                ('cancelado', models.BooleanField(default=False)),
            ],
        ),
    ]
