# Generated by Django 4.0.2 on 2022-02-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoscancelamento',
            name='data_inclusao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoscancelamento',
            name='data_pedido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoscancelamento',
            name='id_pedido',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedidoscancelamento',
            name='nome_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoscancelamento',
            name='status_atual',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
