# Generated by Django 4.0.2 on 2022-02-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_pedidoscancelamento_data_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoscancelamento',
            name='id_pedido',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
