# Generated by Django 4.0.2 on 2022-02-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pedidoscancelamento_id_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoscancelamento',
            old_name='cancelado',
            new_name='cash',
        ),
        migrations.RemoveField(
            model_name='pedidoscancelamento',
            name='data_pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoscancelamento',
            name='status_atual',
        ),
        migrations.AddField(
            model_name='pedidoscancelamento',
            name='corss_border',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoscancelamento',
            name='env_cancelamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoscancelamento',
            name='status_not_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
