# Generated by Django 4.0.2 on 2022-02-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_cancelado_pedidoscancelamento_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoscancelamento',
            name='env_cancelamento',
            field=models.BooleanField(default=True),
        ),
    ]
