# Generated by Django 4.0.2 on 2022-02-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_pedidoscancelamento_env_cancelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoscancelamento',
            name='corss_border',
            field=models.BooleanField(default=True),
        ),
    ]
