# Generated by Django 4.0.2 on 2022-02-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_pedidoscancelamento_corss_border'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoscancelamento',
            name='corss_border',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedidoscancelamento',
            name='env_cancelamento',
            field=models.BooleanField(default=False),
        ),
    ]
